name: Microservices Tigger CI

on:
  push:
    branches: [ main ]
    paths:
     - "src/**"
  workflow_dispatch: {}

permissions:
   contents: read
   packages: write

concurrency: 
  group: microservices-ci-${{ github.ref }}
  cancel-in-progress: false

