name: Microservices Tigger CI

on:
  push:
  workflow_dispatch: 
permissions: 
  contents: read
  packages: write
jobs:
  build:
    strategy:
      matrix:
        service:
          - frontend
          - adservice
          - cartservice
          - checkoutservice
          - currencyservice
          - emailservice
          - paymentservice
          - productcatalogservice
          - recommendationservice
          - shippingservice
          - shoppingassistantservice
        include:
          - service: cartservice
            dockerfile: ./src/cartservice/docker/Dockerfile
    uses: ./.github/workflows/microservice-ci.yaml
    with:
      service: ${{ matrix.service }}
      dockerfile: ${{ matrix.dockerfile }}
    
