name: microservice CI

on:
  workflow_call:
    inputs:
      service:
        type: string
        required: true
jobs:
  build:
    runs-on: ubuntu-latest
    permissions: 
      contents: read
      packages: write
    env:
          SERVICE: ${{ inputs.service }}
    steps:
      - uses: actions/checkout@v4
      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - run: echo "$SERVICE"
      - name: Set image tag
        run: |
          OWNER:"${Hatman025,}"
          echo "IMAGE=ghcr.io/OWNER/$SERVICE:${GITHUB_SHA}" >> "$GITHUB_ENV"
      
      - run: docker build -t "$SERVICE" "./src/$SERVICE"
      - uses: aquasecurity/trivy-action@ed142fd0673e97e23eac54620cfb913e5ce36c25 # v0.36.0
        with:
          image-ref: ${{ inputs.service }}
          severity: HIGH,CRITICAL
          ignore-unfixed: true
          exit-code: 0
        
