name: microservice CI

on:
  workflow_call:
    inputs:
      service:
        type: string
        required: true
jobs:
  echo:
    runs-on: ubuntu-latest
    env:
          SERVICE: ${{ inputs.service }}
    steps:
      - uses: actions/checkout@v4
      - run: echo "$SERVICE"
      - run: docker build -t "$SERVICE" "./$SERVICE"
        
